import Head from 'next/head';
import { ReactNode } from 'react';
import Header from '../Header/Header';
import Footer from '../Footer/Footer';
import classes from './Layout.module.css';
import Container from '../../ui/Container/Container';

interface LayoutProps {
  children: ReactNode;
  title?: string;
}

const Layout = ({ children, title = 'Grow Together App' }: LayoutProps) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={classes.pageContainer}>
        <Header />
        <main className={classes.main}>
          <Container>{children}</Container>
        </main>
        <Footer />
      </div>
    </>
  );
};

export default Layout;
